/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(append_crc32.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(de483541a761081a4686ff1953728f8a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_11/append_crc32.h>
// pydoc.h is automatically generated in the build directory
#include <append_crc32_pydoc.h>

void bind_append_crc32(py::module& m)
{

    using append_crc32 = ::gr::ieee802_11::append_crc32;


    py::class_<append_crc32, gr::block, gr::basic_block, std::shared_ptr<append_crc32>>(
        m, "append_crc32", D(append_crc32))

        .def(py::init(&append_crc32::make),
             py::arg("append") = true,
             D(append_crc32, make))


        ;
}
