#!/bin/bash
if [ $1 ]
then
	result_dir=$1
else 
	now=`date '+%m_%d__%H_%M_%S'`;
	result_dir="result_$now"
fi

mkdir -p $result_dir
rm -rf $result_dir/*

echo ">>> Storing results in ./$result_dir."

for e in {0..3}
do
	for s in `seq 1.0 2 16.0`
	do
	make result=$result_dir n=10 c=1 s=$s o=0 e=$e i=200
	done
done 
./parse.py $result_dir
