#!/bin/bash
if [ $1 ]
then
	result_dir=$1
	mkdir $result_dir
else 
	result_dir=result
fi

echo ">>>Storing results in ./$result_dir."

rm -rf $result_dir/*
for e in {0..3}
do
	for s in  `seq 1.0 2 10.0`
	do
	make n=10 c=1 s=$s o=0 e=$e i=200
	done
done 
./parse.py $result_dir
